"""Add id_file columns

Revision ID: 31bc6fe65dc2
Revises: 
Create Date: 2025-09-03 15:10:36.577408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31bc6fe65dc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('degree_certificate_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('degree_certificate_data', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('id_proof_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('id_proof_data', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('degree_certificate')
        batch_op.drop_column('id_proof')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_proof', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('degree_certificate', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('id_proof_data')
        batch_op.drop_column('id_proof_name')
        batch_op.drop_column('degree_certificate_data')
        batch_op.drop_column('degree_certificate_name')

    # ### end Alembic commands ###
